### ISSUE TITLE
Firefox issue

### ISSUE THREAD

**Issue by arrienc** [WhiteHouse/omb_place#1]
On FF 40.0.2 (OSX) and FF 38.2.0 (Windows 7) the map appears displaced over to the side. So you have to do a horizontal scroll to get it in full view.

![screen shot 2015-08-26 at 12 14 25 pm](https://cloud.githubusercontent.com/assets/2904626/9499217/0c560d8a-4bec-11e5-88fb-b196165abcab.png)

**Comment by ryanbharvey** [comment]
Hi @arrienc, thanks for the bug report!

This was a Drupal integration issue, where the header was apparently 15px taller in Firefox than in other browsers.  I think it should now be fixed.

Let me know if you see it reappear.

**Comment by arrienc** [comment]
It is now working properly in FF, both PC And Mac.
Thanks for this great resource.
