### ISSUE TITLE
Build script dependencies

### ISSUE THREAD

**Issue by mchelen** [WhiteHouse/omb_place#2]
What external tools are needed for the build scripts? I am getting a few "command not found" errors for:

```
uglifyjs
enhancecss
cleancss
```

I fixed the one with `npm install -g uglifyjs` should the same be done for the other commands?

**Comment by ryanbharvey** [comment]
Actually, the dependencies are noted in comments at the top of the two other build scripts.  I'll add them to the README.md so it's a bit more clear.

For the CSS optimization:

```
# Compress CSS files using:
  # CleanCSS (https://github.com/jakubpawlowicz/clean-css)
    # npm install -g clean-css
  # CleanCSS (https://github.com/jakubpawlowicz/enhance-css)
    # npm install -g enhance-css
```

For the JS optimization:

```
# Script requires uglify-js v2 (https://github.com/mishoo/UglifyJS2)
  # npm install uglify-js -g
```
