### ISSUE TITLE
Zoom on scroll

### ISSUE THREAD

**Issue by s7726** [WhiteHouse/omb_place#5]
The typical interface for a web based map uses the scroll wheel to zoom. This map does not, making it confusing and cumbersome to navigate.

**Comment by ryanbharvey** [comment]
Thanks for the feedback.  Disabling zoom via scroll wheel was one of the decisions made early during development of the map.  Perhaps in a future iteration, we will revisit that decision.

That said, re-enabling is easy: just remove [line 1429 in main.js](https://github.com/WhiteHouse/omb_place/blob/master/assets/main.js#L1429).  Please feel free to do this in your own fork of the map if it meets your needs.
