### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by arrienc** [WhiteHouse/omb_place#6]
On this page:
https://www.whitehouse.gov/omb/place/datasets

Under NEA Our Town it says:
The Our Town imitative supports ...

Should say:
The Our Town initiative supports ...

Hope this is the right venue for this fix.
Thanks

**Comment by ryanbharvey** [comment]
Thanks for the report.  We've updated the typo in the data system used to generate these data files, so that this will be fixed in the next release.  I'll also update the file in this repo, so that anyone forking it will have the correct data.
